name: Java CI/CD Pipeline

# Trigger the workflow on push and pull requests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Java environment
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Compile Java files
    - name: Compile Java files
      run: |
        echo "🔨 Compiling Java files..."
        find . -name "*.java" -print0 | while IFS= read -r -d '' file; do
          echo "Compiling: $file"
          javac "$file"
          if [ $? -eq 0 ]; then
            echo "✅ Successfully compiled: $file"
          else
            echo "❌ Failed to compile: $file"
            exit 1
          fi
        done
    
    # Clean up compiled files
    - name: Cleanup
      run: |
        echo "🧹 Cleaning up compiled files..."
        find . -name "*.class" -delete
        echo "✅ Cleanup completed!"